<?php
	require_once "google add entry func.php";
	
	INCLUDE_ONCE "admin_user_administration_func.php";
	INCLUDE_ONCE "admin_constants.php";
	
	if(getUserRole(getUserEmail()) > $GLOBALS["ROLES_SUBADMIN"]) {
		header("HTTP/1.0 404 Not Found");
		die();
	}
?>

<!DOCTYPE html>
<html>
	<head>
		<!-- Special version of Bootstrap that only affects content wrapped in .bootstrap-iso -->
		<link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" /> 
	</head>
<!-- Inline CSS based on choices in "Settings" tab -->
<style>.required-field {color: red;} .bootstrap-iso .formden_header h2, .bootstrap-iso .formden_header p, .bootstrap-iso form{font-family: Arial, Helvetica, sans-serif; color: black}.bootstrap-iso form button, .bootstrap-iso form button:hover{color: white !important;}.bootstrap-iso .form-control:focus { border-color: #ffe314;  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(255, 227, 20, 0.6); box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(255, 227, 20, 0.6);} .asteriskField{color: red;}.bootstrap-iso form .input-group-addon {color:#4e4f46; background-color: #eeeeee; border-radius: 4px; padding-left:12px}</style>

	<body>
		<!-- HTML Form (wrapped in a .bootstrap-iso div) -->
		<div class="bootstrap-iso">
		 <div class="container-fluid">
		  <div class="row">
		   <div class="col-md-6 col-sm-6 col-xs-12">
			<form method="post">
			 <div class="form-group ">
			  <label class="control-label " for="name">
			   Name des Events <span class="required-field">*</span>
			  </label>
			  <input required class="form-control" id="name" name="eventname" type="text" value="<?php echo $title; ?>"/>
			 </div>
			 <div class="form-group ">
			  <label id="lab" class="control-label " for="select">
			   Kalender <span class="required-field">*</span>
			  </label>
			  <p for="lab">Nur Termine im externen Kalender werden im Newsflash sichtbar sein.</p>
			  <select class="select form-control" id="select" name="selectCalendar" value="both"/>
			   <option value="intern">
				Interner Kalender 
			   </option>
			   <option value="extern">
				Externer Kalender
			   </option>
			   <option value="both">
				Beide Kalender
			   </option>
			  </select>
			 </div>
			 <div class="form-group ">
			  <label class="control-label " for="text">
			   Ort <i>(Optional)</i>
			  </label>
			  <input class="form-control" id="text" name="place" value="<?php echo $place?>" type="text"/>
			 </div>
			 <div class="form-group ">
			  <label class="control-label " for="message">
			   Message
			  </label>
			  <textarea class="form-control" placeholder="Beschreiben Sie den Termin in ein paar Sätzen ..." cols="40" id="message" name="message" rows="8"><?php echo $desc?></textarea>
			 </div>
			 <div class="form-group ">
			  <label class="control-label " for="date">
			   Datum <span class="required-field">*</span>
			  </label>
			  <input required class="form-control" id="date" value="<?php echo $date?>" name="date" placeholder="Tag.Monat.Jahr" type="text"/>
			 </div>
			 <div class="form-group ">
			  <label class="control-label " for="select1">
			   Uhrzeit: <span class="required-field">*</span>   
			  </label>
			  <select required class="select form-control" onchange="refillTo()" selected="<?php echo $firstTime ?>" id="selectFrom" name="selectFrom" style="display: inline-block;width:20%;">
				<!-- Generated by code -->
			  </select>
				   <label class="control-label " for="select1">
			   bis:
			  </label>
			  <select class="select form-control" id="selectTo" name="selectTo" style="width: 20%;display: inline;">
			   <!-- Code -->
			  </select>
			 </div>
			 <div class="form-group">
			 </div>
			 <div class="form-group">
			  <div>
			   <button class="btn btn-primary" name="form-sent" type="submit">
				<?php echo $buttonText?>
			   </button> oder <a href="../Startseite.php">Zurück zur Startseite</a>
			  </div>
			 </div>
			</form>
		   </div>
		  </div>
		 </div>
		</div>
	</body>

<!-- Extra JavaScript/CSS added manually in "Settings" tab -->
<!-- Include jQuery -->
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

<!-- Include Date Range Picker -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

<script>
    $(document).ready(function(){
        var date_input=$('input[name="date"]'); //our date input has the name "date"
        var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
        date_input.datepicker({
            format: 'dd.mm.yyyy',
            container: container,
            todayHighlight: true,
            autoclose: true,
        })
    })
	
	// Startup
	fillSelection(1,23,'selectFrom');
	fillSelection(2,24,'selectTo');
	start();
	
	function start() {
		document.getElementById('selectFrom').selectedIndex = <?php echo $firstTime?> - 1;
		document.getElementById('selectTo').selectedIndex = <?php echo $secondTime?> - 1;
		
		if("extern" == "<?php echo $selectedCalendar?>") {
			document.getElementById('select').selectedIndex = 1;
		}
	}
	
function validate(text) {

	if(text == "Eintrag löschen") {
		return confirm('Wollen Sie diesen Eintrag wirklich löschen?');
	}
}
	

	
	function fillSelection(minimum, maximum, select) {
		var min = minimum;
		var max = maximum;
		var element = document.getElementById(select);

		for (var i = min; i<=max; i++){
			var opt = document.createElement('option');
			opt.value = i-1;
			opt.innerHTML = i + " Uhr";
			element.appendChild(opt);
		}
	}
	
	function refillTo() {
		document.getElementById('selectTo').innerHTML = "";
		fillSelection(document.getElementById('selectFrom').selectedIndex + 2, 24, 'selectTo');
	}

	
	
</script>
</html>